# Generated by Django 3.0.7 on 2020-06-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plant_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_id', models.CharField(max_length=2)),
                ('plant_name', models.CharField(max_length=50)),
                ('growth_day', models.IntegerField()),
                ('distance', models.FloatField()),
                ('water_flowrate', models.FloatField()),
                ('last_irrigated', models.DateTimeField()),
            ],
        ),
    ]
