# Generated by Django 3.0.7 on 2020-06-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('h2os', 'add_plant_data'),
    ]

    operations = [
    ]
