# Generated by Django 3.0.7 on 2020-06-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('h2os', '0001_auto_20200618_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='chart',
        ),
    ]
