# Generated by Django 3.0.7 on 2020-06-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h2os', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant_group',
            name='growth_day',
            field=models.CharField(max_length=4),
        ),
    ]
