# Generated by Django 3.0.7 on 2020-06-18 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('h2os', '0002_remove_plant_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant_group',
            name='loc_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='Water_usage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('usage', models.FloatField(verbose_name='Water usage(L)')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='h2os.Plant_group')),
            ],
            options={
                'verbose_name_plural': 'Water_usage',
                'db_table': 'Water_Usage',
            },
        ),
    ]
