# Generated by Django 3.0.7 on 2020-06-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h2os', '0002_auto_20200614_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant_group',
            name='loc_id',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
