# Generated by Django 3.0.7 on 2020-06-20 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('h2os', '0003_auto_20200618_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'verbose_name_plural': 'Plants'},
        ),
        migrations.AlterModelOptions(
            name='plant_group',
            options={'verbose_name_plural': 'Plantgroups'},
        ),
        migrations.AlterField(
            model_name='water_usage',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='h2os.Plant_group'),
        ),
    ]
