# Generated by Django 3.0.7 on 2020-06-22 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('h2os', '0004_auto_20200620_1755'),
        ('h2os', '0005_auto_20200620_1733'),
    ]

    operations = [
    ]
