# Generated by Django 3.0.7 on 2020-06-23 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('h2os', '0008_auto_20200623_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant_group',
            old_name='distance',
            new_name='area',
        ),
        migrations.AlterField(
            model_name='water_usage',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='h2os.Plant_group'),
        ),
    ]
