# Generated by Django 3.0.7 on 2020-07-05 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('h2os', '0016_auto_20200704_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pan_data',
            name='system_change',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='water_usage',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='h2os.Plant_group'),
        ),
    ]
