# Generated by Django 3.0.7 on 2020-07-05 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('h2os', '0019_auto_20200705_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water_usage',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h2os.Plant_group'),
        ),
    ]
