# Generated by Django 3.0.7 on 2020-06-18 14:59

from django.db import migrations
import json


def add_data(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Plant = apps.get_model('h2os', 'Plant')
    with open("./../data/cropdata.json") as crop:
        info = json.load(crop)
    for k, v in info.items():
        plant = Plant(name=k,
                      initial_kc=v["initial_kc"],
                      mid_kc=v["mid_kc"],
                      end_kc=v["end_kc"],
                      initial_length=v["initial_length"],
                      interpolate_length=v["interpolate_length"],
                      mid_length=v["mid_length"],
                      end_length=v["end_length"],
                      )
        plant.save()


class Migration(migrations.Migration):

    dependencies = [
        ('h2os', '0007_auto_20200618_1157'),
    ]

    operations = [
        migrations.RunPython(add_data),
    ]
